# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json
backend:
  name: github
  repo: ky3ow/test-landing

media_folder: "src/assets/images"
public_folder: "src/assets/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - name: about
        file: "src/content/pages/about.md"
        fields:
          - label: Title
            name: title
            widget: string
          - label: Description
            name: description
            widget: markdown
          - label: Body
            name: body
            widget: markdown
          - label: Cover
            name: cover
            required: false
            widget: image
          - label: Members
            name: members
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Portrait
                name: portrait
                widget: image
      - name: home
        file: "src/content/pages/home.md"
        fields:
          - label: Hero Title
            name: title
            widget: string
          - label: Hero Description
            name: description
            widget: markdown
          - label: Body Content
            name: body
            widget: markdown
          - label: Hero Image
            name: cover
            required: false
            widget: image
          - label: CTA Text
            name: cta_text
            widget: string
          - label: CTA Link
            name: cta_link
            widget: string
